# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160318_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('validation', models.CharField(max_length=200)),
                ('invitation', models.CharField(max_length=200)),
                ('percent', models.IntegerField()),
            ],
        ),
    ]
