# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_points'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Points',
            new_name='PointsT',
        ),
    ]
