# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20160319_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointst',
            name='percent',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='send_points',
            name='percent',
            field=models.CharField(max_length=200),
        ),
    ]
